version: "3.9"

services:
  backend:
    build: .
    command: flask run --debug --host=0.0.0.0 --port=5000
    env_file:
      - .env
    environment:
      FLASK_APP: app.py
    volumes:
      - .:/app
    depends_on:
      - postgres
      - couchdb
    expose:
      - "5000"

  frontend:
    image: nginx:alpine
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  couchdb:
    image: couchdb:3
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  postgres_data:
  couchdb_data:
