version: "3.9"

services:
  backend:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
      - couchdb
    expose:
      - "5000"

  frontend:
    image: nginx:alpine
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  couchdb:
    image: couchdb:3
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  postgres_data:
  couchdb_data:
